# Generated by Django 4.2 on 2023-05-15 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 15, 11, 37, 6, 250970)),
        ),
    ]
