# Generated by Django 4.2 on 2023-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_ratings'),
        ),
    ]
