# Generated by Django 4.2 on 2023-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_userrating_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('b', 'busy')], default='a', max_length=1),
        ),
    ]
