# Generated by Django 4.2 on 2023-04-14 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_establishments_userrating_passport_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.TimeField(auto_created=datetime.datetime(2023, 4, 14, 20, 43, 40, 149477)),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
