# Generated by Django 4.2 on 2023-04-14 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0003_alter_passport_date_create_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrangement',
            new_name='Arrangements',
        ),
        migrations.RemoveField(
            model_name='establishments',
            name='establishment',
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.TimeField(auto_created=datetime.datetime(2023, 4, 14, 21, 28, 33, 173326)),
        ),
    ]
