# Generated by Django 4.2 on 2023-04-14 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0004_rename_arrangement_arrangements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.TimeField(auto_created=datetime.datetime(2023, 4, 14, 21, 37, 45, 41827)),
        ),
    ]
