# Generated by Django 4.2 on 2023-04-14 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0005_alter_establishments_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishments',
            name='address',
        ),
        migrations.RemoveField(
            model_name='establishments',
            name='phone',
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 14, 22, 18, 11, 853172)),
        ),
    ]
